language: node_js
node_js:
- 8
before_script:
- npm i -g add codecov
script:
- npm run eslint
- npm run flow
- npm run cover -- --runInBand
after_success:
- codecov
before_deploy: npm postversion
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    repo: intel-hpdd/GUI
