language: generic
sudo: required
services:
  - docker
addons:
  apt:
    update: true
jobs:
  include:
    - stage: test
      env: Type='Test Checks'
      language: node_js
      node_js:
        - "8"
      before_script:
        - npm i -g add codecov
      script:
        - npm run eslint
        - npm run flow
        - npm run cover -- --runInBand
      after_success:
        - codecov
    - stage: deploy-npm
      env: Type='NPM Deploy'
      before_deploy:
        - npm i
        - npm run postversion
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        skip_cleanup: true
        api_key: "$NPM_TOKEN"
        on:
          all_branches: true
          repo: whamcloud/GUI
    - stage: deploy-copr
      env: Type='Copr deploy'
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-devel
        - export PACKAGE=iml-gui
        - export SPEC=iml-gui.spec
        - export PROD=False
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e PROD="$PROD" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
      on:
        all_branches: true
    - stage: cd
      git:
        depth: 999999
      env: Type='Continuous Deployment'
      script:
        - include/travis/copr-deploy.sh prepare
        - ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build_srpm"
stages:
  - test
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+-1.*$
  - name: deploy-copr
    if: branch =~ ^v\d+\.\d+\.\d+-.+$
  - name: cd
    if: branch = master AND type = push AND fork = false
